### ISSUE TITLE
[FEAT] URL 세팅

### ISSUE THREAD

**Issue by JMine97** [project-sin/sin#10]
**Subject**
URL 세팅

**Detail**
사용할 URL을 정리한다

**Comment by JMine97** [comment]
![image](https://user-images.githubusercontent.com/52027965/125196098-753e0200-e293-11eb-841d-33b13408914e.png)
https://drive.google.com/drive/folders/1_Ys8YGwHeL8fka7gPtSZoI7X4FO0YxLl
일단 이거 기본 틀로 하고 작성하면서 하나하나 추가할까요?

**Comment by khdscor** [comment]
확인했습니다!  기본틀도 잘짜셨고 점점 추가해나가면 좋을것같네요~ 
궁금한게 있는데 모두 GET 요청인건가요? 그리고 상품후기에서 mypage_review 로끝나잖아요? 그러면 내가 작성한 상품후기 리스트를 보여주는 건가요?

**Comment by JMine97** [comment]
> 확인했습니다! 기본틀도 잘짜셨고 점점 추가해나가면 좋을것같네요~
> 궁금한게 있는데 모두 GET 요청인건가요? 그리고 상품후기에서 mypage_review 로끝나잖아요? 그러면 내가 작성한 상품후기 리스트를 보여주는 건가요?

**Comment by JMine97** [comment]
> 확인했습니다! 기본틀도 잘짜셨고 점점 추가해나가면 좋을것같네요~
> 궁금한게 있는데 모두 GET 요청인건가요? 그리고 상품후기에서 mypage_review 로끝나잖아요? 그러면 내가 작성한 상품후기 리스트를 보여주는 건가요?

일단 모두 get 요청으로 생각했습니다!
마켓컬리 페이지에서 보면 상품후기 탭 들어가면 작성가능 후기(구매는 했지만 아직 후기를 작성하지 않은 상품들 출력)가 기본으로 나오고 작성완료후기 탭을 누르면 작성 완료한 후기들을 볼 수 있습니다!

**Comment by khdscor** [comment]
아하 어떤 구조인지 이해했습니다! 감사합니다~
